// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/internal/runtime (interfaces: Runtime,RunHandle,StreamHandle)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	events "github.com/agenticenv/agent-sdk-go/internal/events"
	runtime "github.com/agenticenv/agent-sdk-go/internal/runtime"
	types "github.com/agenticenv/agent-sdk-go/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockRuntime) Approve(arg0 context.Context, arg1 string, arg2 types.ApprovalStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockRuntimeMockRecorder) Approve(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockRuntime)(nil).Approve), arg0, arg1, arg2)
}

// Close mocks base method.
func (m *MockRuntime) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRuntimeMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRuntime)(nil).Close))
}

// GetRunHandle mocks base method.
func (m *MockRuntime) GetRunHandle(arg0 context.Context, arg1 string) (runtime.RunHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunHandle", arg0, arg1)
	ret0, _ := ret[0].(runtime.RunHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunHandle indicates an expected call of GetRunHandle.
func (mr *MockRuntimeMockRecorder) GetRunHandle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunHandle", reflect.TypeOf((*MockRuntime)(nil).GetRunHandle), arg0, arg1)
}

// GetStreamHandle mocks base method.
func (m *MockRuntime) GetStreamHandle(arg0 context.Context, arg1 string) (runtime.StreamHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamHandle", arg0, arg1)
	ret0, _ := ret[0].(runtime.StreamHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamHandle indicates an expected call of GetStreamHandle.
func (mr *MockRuntimeMockRecorder) GetStreamHandle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamHandle", reflect.TypeOf((*MockRuntime)(nil).GetStreamHandle), arg0, arg1)
}

// Run mocks base method.
func (m *MockRuntime) Run(arg0 context.Context, arg1 *runtime.RunRequest) (runtime.RunHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(runtime.RunHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockRuntimeMockRecorder) Run(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRuntime)(nil).Run), arg0, arg1)
}

// Stream mocks base method.
func (m *MockRuntime) Stream(arg0 context.Context, arg1 *runtime.RunRequest) (runtime.StreamHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", arg0, arg1)
	ret0, _ := ret[0].(runtime.StreamHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockRuntimeMockRecorder) Stream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockRuntime)(nil).Stream), arg0, arg1)
}

// MockRunHandle is a mock of RunHandle interface.
type MockRunHandle struct {
	ctrl     *gomock.Controller
	recorder *MockRunHandleMockRecorder
}

// MockRunHandleMockRecorder is the mock recorder for MockRunHandle.
type MockRunHandleMockRecorder struct {
	mock *MockRunHandle
}

// NewMockRunHandle creates a new mock instance.
func NewMockRunHandle(ctrl *gomock.Controller) *MockRunHandle {
	mock := &MockRunHandle{ctrl: ctrl}
	mock.recorder = &MockRunHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunHandle) EXPECT() *MockRunHandleMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockRunHandle) Cancel(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockRunHandleMockRecorder) Cancel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockRunHandle)(nil).Cancel), arg0)
}

// Done mocks base method.
func (m *MockRunHandle) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockRunHandleMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockRunHandle)(nil).Done))
}

// Get mocks base method.
func (m *MockRunHandle) Get(arg0 context.Context) (*types.AgentRunResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*types.AgentRunResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRunHandleMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRunHandle)(nil).Get), arg0)
}

// ID mocks base method.
func (m *MockRunHandle) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockRunHandleMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockRunHandle)(nil).ID))
}

// Status mocks base method.
func (m *MockRunHandle) Status(arg0 context.Context) (types.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0)
	ret0, _ := ret[0].(types.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockRunHandleMockRecorder) Status(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockRunHandle)(nil).Status), arg0)
}

// MockStreamHandle is a mock of StreamHandle interface.
type MockStreamHandle struct {
	ctrl     *gomock.Controller
	recorder *MockStreamHandleMockRecorder
}

// MockStreamHandleMockRecorder is the mock recorder for MockStreamHandle.
type MockStreamHandleMockRecorder struct {
	mock *MockStreamHandle
}

// NewMockStreamHandle creates a new mock instance.
func NewMockStreamHandle(ctrl *gomock.Controller) *MockStreamHandle {
	mock := &MockStreamHandle{ctrl: ctrl}
	mock.recorder = &MockStreamHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamHandle) EXPECT() *MockStreamHandleMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockStreamHandle) Cancel(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockStreamHandleMockRecorder) Cancel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockStreamHandle)(nil).Cancel), arg0)
}

// Done mocks base method.
func (m *MockStreamHandle) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockStreamHandleMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockStreamHandle)(nil).Done))
}

// Events mocks base method.
func (m *MockStreamHandle) Events(arg0 context.Context, arg1 int64) (<-chan events.AgentEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", arg0, arg1)
	ret0, _ := ret[0].(<-chan events.AgentEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockStreamHandleMockRecorder) Events(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockStreamHandle)(nil).Events), arg0, arg1)
}

// Get mocks base method.
func (m *MockStreamHandle) Get(arg0 context.Context) (*types.AgentRunResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*types.AgentRunResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStreamHandleMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStreamHandle)(nil).Get), arg0)
}

// ID mocks base method.
func (m *MockStreamHandle) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockStreamHandleMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockStreamHandle)(nil).ID))
}

// Status mocks base method.
func (m *MockStreamHandle) Status(arg0 context.Context) (types.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0)
	ret0, _ := ret[0].(types.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockStreamHandleMockRecorder) Status(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockStreamHandle)(nil).Status), arg0)
}
