// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/internal/runtime (interfaces: WorkerRuntime)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	runtime "github.com/agenticenv/agent-sdk-go/internal/runtime"
	types "github.com/agenticenv/agent-sdk-go/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockWorkerRuntime is a mock of WorkerRuntime interface.
type MockWorkerRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerRuntimeMockRecorder
}

// MockWorkerRuntimeMockRecorder is the mock recorder for MockWorkerRuntime.
type MockWorkerRuntimeMockRecorder struct {
	mock *MockWorkerRuntime
}

// NewMockWorkerRuntime creates a new mock instance.
func NewMockWorkerRuntime(ctrl *gomock.Controller) *MockWorkerRuntime {
	mock := &MockWorkerRuntime{ctrl: ctrl}
	mock.recorder = &MockWorkerRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerRuntime) EXPECT() *MockWorkerRuntimeMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWorkerRuntime) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockWorkerRuntimeMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorkerRuntime)(nil).Close))
}

// GetRunHandle mocks base method.
func (m *MockWorkerRuntime) GetRunHandle(arg0 context.Context, arg1 string) (runtime.RunHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunHandle", arg0, arg1)
	ret0, _ := ret[0].(runtime.RunHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunHandle indicates an expected call of GetRunHandle.
func (mr *MockWorkerRuntimeMockRecorder) GetRunHandle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunHandle", reflect.TypeOf((*MockWorkerRuntime)(nil).GetRunHandle), arg0, arg1)
}

// GetStreamHandle mocks base method.
func (m *MockWorkerRuntime) GetStreamHandle(arg0 context.Context, arg1 string) (runtime.StreamHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamHandle", arg0, arg1)
	ret0, _ := ret[0].(runtime.StreamHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamHandle indicates an expected call of GetStreamHandle.
func (mr *MockWorkerRuntimeMockRecorder) GetStreamHandle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamHandle", reflect.TypeOf((*MockWorkerRuntime)(nil).GetStreamHandle), arg0, arg1)
}

// OnApproval mocks base method.
func (m *MockWorkerRuntime) OnApproval(arg0 context.Context, arg1 string, arg2 types.ApprovalStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnApproval", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnApproval indicates an expected call of OnApproval.
func (mr *MockWorkerRuntimeMockRecorder) OnApproval(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnApproval", reflect.TypeOf((*MockWorkerRuntime)(nil).OnApproval), arg0, arg1, arg2)
}

// Run mocks base method.
func (m *MockWorkerRuntime) Run(arg0 context.Context, arg1 *runtime.RunRequest) (runtime.RunHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(runtime.RunHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockWorkerRuntimeMockRecorder) Run(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockWorkerRuntime)(nil).Run), arg0, arg1)
}

// Start mocks base method.
func (m *MockWorkerRuntime) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockWorkerRuntimeMockRecorder) Start(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWorkerRuntime)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockWorkerRuntime) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockWorkerRuntimeMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWorkerRuntime)(nil).Stop))
}

// Stream mocks base method.
func (m *MockWorkerRuntime) Stream(arg0 context.Context, arg1 *runtime.RunRequest) (runtime.StreamHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", arg0, arg1)
	ret0, _ := ret[0].(runtime.StreamHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockWorkerRuntimeMockRecorder) Stream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockWorkerRuntime)(nil).Stream), arg0, arg1)
}
