// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/agent (interfaces: AgentEvent)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	events "github.com/agenticenv/agent-sdk-go/internal/events"
	gomock "github.com/golang/mock/gomock"
)

// MockAgentEvent is a mock of AgentEvent interface.
type MockAgentEvent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentEventMockRecorder
}

// MockAgentEventMockRecorder is the mock recorder for MockAgentEvent.
type MockAgentEventMockRecorder struct {
	mock *MockAgentEvent
}

// NewMockAgentEvent creates a new mock instance.
func NewMockAgentEvent(ctrl *gomock.Controller) *MockAgentEvent {
	mock := &MockAgentEvent{ctrl: ctrl}
	mock.recorder = &MockAgentEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentEvent) EXPECT() *MockAgentEventMockRecorder {
	return m.recorder
}

// Timestamp mocks base method.
func (m *MockAgentEvent) Timestamp() *int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timestamp")
	ret0, _ := ret[0].(*int64)
	return ret0
}

// Timestamp indicates an expected call of Timestamp.
func (mr *MockAgentEventMockRecorder) Timestamp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timestamp", reflect.TypeOf((*MockAgentEvent)(nil).Timestamp))
}

// ToJSON mocks base method.
func (m *MockAgentEvent) ToJSON() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToJSON")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToJSON indicates an expected call of ToJSON.
func (mr *MockAgentEventMockRecorder) ToJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToJSON", reflect.TypeOf((*MockAgentEvent)(nil).ToJSON))
}

// Type mocks base method.
func (m *MockAgentEvent) Type() events.AgentEventType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(events.AgentEventType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockAgentEventMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockAgentEvent)(nil).Type))
}
