// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/agent (interfaces: AgentRun)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/agenticenv/agent-sdk-go/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockAgentRun is a mock of AgentRun interface.
type MockAgentRun struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRunMockRecorder
}

// MockAgentRunMockRecorder is the mock recorder for MockAgentRun.
type MockAgentRunMockRecorder struct {
	mock *MockAgentRun
}

// NewMockAgentRun creates a new mock instance.
func NewMockAgentRun(ctrl *gomock.Controller) *MockAgentRun {
	mock := &MockAgentRun{ctrl: ctrl}
	mock.recorder = &MockAgentRunMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRun) EXPECT() *MockAgentRunMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockAgentRun) Cancel(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockAgentRunMockRecorder) Cancel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockAgentRun)(nil).Cancel), arg0)
}

// Done mocks base method.
func (m *MockAgentRun) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockAgentRunMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockAgentRun)(nil).Done))
}

// Get mocks base method.
func (m *MockAgentRun) Get(arg0 context.Context) (*types.AgentRunResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*types.AgentRunResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentRunMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentRun)(nil).Get), arg0)
}

// ID mocks base method.
func (m *MockAgentRun) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockAgentRunMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockAgentRun)(nil).ID))
}

// Status mocks base method.
func (m *MockAgentRun) Status(arg0 context.Context) (types.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0)
	ret0, _ := ret[0].(types.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockAgentRunMockRecorder) Status(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockAgentRun)(nil).Status), arg0)
}
