// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/agent (interfaces: AgentStream)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	events "github.com/agenticenv/agent-sdk-go/internal/events"
	types "github.com/agenticenv/agent-sdk-go/internal/types"
	agent "github.com/agenticenv/agent-sdk-go/pkg/agent"
	gomock "github.com/golang/mock/gomock"
)

// MockAgentStream is a mock of AgentStream interface.
type MockAgentStream struct {
	ctrl     *gomock.Controller
	recorder *MockAgentStreamMockRecorder
}

// MockAgentStreamMockRecorder is the mock recorder for MockAgentStream.
type MockAgentStreamMockRecorder struct {
	mock *MockAgentStream
}

// NewMockAgentStream creates a new mock instance.
func NewMockAgentStream(ctrl *gomock.Controller) *MockAgentStream {
	mock := &MockAgentStream{ctrl: ctrl}
	mock.recorder = &MockAgentStreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentStream) EXPECT() *MockAgentStreamMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockAgentStream) Approve(arg0 context.Context, arg1 string, arg2 types.ApprovalStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockAgentStreamMockRecorder) Approve(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockAgentStream)(nil).Approve), arg0, arg1, arg2)
}

// Cancel mocks base method.
func (m *MockAgentStream) Cancel(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockAgentStreamMockRecorder) Cancel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockAgentStream)(nil).Cancel), arg0)
}

// Done mocks base method.
func (m *MockAgentStream) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockAgentStreamMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockAgentStream)(nil).Done))
}

// Events mocks base method.
func (m *MockAgentStream) Events(arg0 context.Context, arg1 ...agent.AgentStreamOption) (<-chan events.AgentEvent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Events", varargs...)
	ret0, _ := ret[0].(<-chan events.AgentEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockAgentStreamMockRecorder) Events(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockAgentStream)(nil).Events), varargs...)
}

// Get mocks base method.
func (m *MockAgentStream) Get(arg0 context.Context) (*types.AgentRunResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*types.AgentRunResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentStreamMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentStream)(nil).Get), arg0)
}

// ID mocks base method.
func (m *MockAgentStream) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockAgentStreamMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockAgentStream)(nil).ID))
}

// Status mocks base method.
func (m *MockAgentStream) Status(arg0 context.Context) (types.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0)
	ret0, _ := ret[0].(types.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockAgentStreamMockRecorder) Status(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockAgentStream)(nil).Status), arg0)
}
