// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agenticenv/agent-sdk-go/pkg/agent/runtime (interfaces: RuntimeFactory)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	runtime "github.com/agenticenv/agent-sdk-go/internal/runtime"
	runtime0 "github.com/agenticenv/agent-sdk-go/pkg/agent/runtime"
	gomock "github.com/golang/mock/gomock"
)

// MockRuntimeFactory is a mock of RuntimeFactory interface.
type MockRuntimeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeFactoryMockRecorder
}

// MockRuntimeFactoryMockRecorder is the mock recorder for MockRuntimeFactory.
type MockRuntimeFactoryMockRecorder struct {
	mock *MockRuntimeFactory
}

// NewMockRuntimeFactory creates a new mock instance.
func NewMockRuntimeFactory(ctrl *gomock.Controller) *MockRuntimeFactory {
	mock := &MockRuntimeFactory{ctrl: ctrl}
	mock.recorder = &MockRuntimeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeFactory) EXPECT() *MockRuntimeFactoryMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockRuntimeFactory) Build(arg0 *runtime0.RuntimeParams, arg1 bool) (runtime.Runtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", arg0, arg1)
	ret0, _ := ret[0].(runtime.Runtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockRuntimeFactoryMockRecorder) Build(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockRuntimeFactory)(nil).Build), arg0, arg1)
}

// Name mocks base method.
func (m *MockRuntimeFactory) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockRuntimeFactoryMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockRuntimeFactory)(nil).Name))
}

// Validate mocks base method.
func (m *MockRuntimeFactory) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockRuntimeFactoryMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockRuntimeFactory)(nil).Validate))
}
